### PR TITLE
Add vignette

### PR DESCRIPTION
**Pull request by ivyleavedtoadflax**
Add vignette to provide detailed walkthrough of package and as a template for producing publication. Save copy of vignette used for each publication to document and comment on the analysis for each release.

### CODE REVIEW

**Comment by ivyleavedtoadflax** [comment]
This is failing because knitr is not available on travis/appveyor: https://travis-ci.org/DCMSstats/eesectors/builds/286074134?utm_source=github_status&utm_medium=notification

screen shot 2017-10-10 at 16 23 48

**Comment by ivyleavedtoadflax** [comment]
Trying to refresh travis cache - this may fix the issue.

**Comment by ivyleavedtoadflax** [comment]
Some info on this error here: 
* https://github.com/travis-ci/travis-ci/issues/5687
* https://stackoverflow.com/questions/44997335/travis-ci-knitr-not-found-in-loadvignettebuilder

**Comment by ivyleavedtoadflax** [comment]
See this issue on preventing travis from building vignettes: 

* https://github.com/travis-ci/travis-ci/issues/4619

**Comment by ivyleavedtoadflax** [comment]
This is now failing here: https://travis-ci.org/DCMSstats/eesectors/builds/286462851#L1046

screen shot 2017-10-11 at 12 05 49

**Review by mammykins — APPROVED** [review]
:shipit: A sensible workaround to travis build failure. A good start to the vignette.

**Pull request merged**
