### PR TITLE
Add error logging using futile.logger for year_sector_data

### PR DESCRIPTION
**Pull request by mammykins**
Addresses issue #105 for the year_sector_data.R

Is this what you were after @ivyleavedtoadflax?

### CODE REVIEW

**Comment by mammykins** [comment]
@ivyleavedtoadflax 

* checking package dependencies ... ERROR
Package required but not available: ‘futile.logger’

I've got it included in the DESCRIPTION file... Similar problem with this package in RAP companion Travis build

**Comment by ivyleavedtoadflax** [comment]
hmmm

**Comment by ivyleavedtoadflax** [comment]
Perfect, that's just what i was thinking about - good work @mammykins. I think we need to flush the travis cache to get it to build right - will try now.

**Review by ivyleavedtoadflax — APPROVED** [review]
This looks good to me. @maxwell8888 can you have a quick look and make sure you are happy with this. My suggestion is that we roll out this kind of logging across all the substantial function sin the package. Should be particularly useful for the `combine_gva()` function. It would be good to include debug logs to record the size and shape of datasets as they are imported, so you can track any obvious errors as they occur.

**Comment by maxwell8888** [comment]
looks good to me. where does the log get saved to?

**Review by maxwell8888 — APPROVED** [review]
looks good

**Comment by mammykins** [comment]
@maxwell8888  log will get saved in the working directory, or you can specify

**Pull request merged**
