### PR TITLE
[WIP] Add example working_file.xlsx

### PR DESCRIPTION
**Pull request by maxwell8888**
no errors using extract functions then combine_GVA()
but fails statistical tests of year_sector_data()
included function to get file path - see README
have not written any tests yet

### CODE REVIEW

**Comment by ivyleavedtoadflax** [comment]
Amazing, I'll have a look tomorrow. Great stuff @maxwell8888.

**Comment by maxwell8888** [comment]
@ivyleavedtoadflax  I've had a stab at creating an example file - it ended up taking longer than I though it would - I forgot how painful VBA and excel can be. I need to investigate why the class is failing - could be because I've populated all the numbers with 111... I'm busy tomorrow but will try and get it finished on Friday. Just though I'd show you what I've done so far so that I can create my first PR :)
Also, I realise I didn't need to include the README_files figures, and also why line 36 in READ.md has changed?

**Comment by ivyleavedtoadflax** [comment]
@maxwell8888 just slacked you about this.

**Review by ivyleavedtoadflax — CHANGES_REQUESTED** [review]
This looks good then @maxwell8888. Can you just add a note to the spreadsheet to indicate that this is dummy data? Then good to merge.

**Comment by maxwell8888** [comment]
@ivyleavedtoadflax I was going to try and get it so setting year_sector_data class doesn't fail - is it not worth doing this? I think it might be a case of using random numbers instead of 111 - was going to try friday but didn't get round to it.

**Comment by ivyleavedtoadflax** [comment]
Ahh interesting, I wasn't aware that it was failing. What's the error you are getting? We should build a test to capture this error.

**Comment by maxwell8888** [comment]
@ivyleavedtoadflax "Checking for the correct number of rows..." fails - some 2015 data is missing. I'm looking into it now and I'll write a test.

**Comment by ivyleavedtoadflax** [comment]
That's interesting: that fail is not captured in the current tests on travis. From memory, the check for the right number of rows just multiplies the number of sectors against the number of years.

**Comment by maxwell8888** [comment]
@ivyleavedtoadflax yes but it is just a check that is run as part of running year_sector_data() i.e. is in in test_that so wouldn't be run by travis

**Comment by ivyleavedtoadflax** [comment]
the test_that tests are run by travis too

**Comment by maxwell8888** [comment]
*isn't in test_that

**Comment by ivyleavedtoadflax** [comment]
Ah of course. It sounds like it might actually be a problem with the example data rather than the function.

**Comment by maxwell8888** [comment]
yep - it only happens run using the example data

**Comment by ivyleavedtoadflax** [comment]
This is probably an indication that we need more explicit error messages too!

**Comment by maxwell8888** [comment]
I think some checking in combine_GVA would be useful - I'm going through it now to work out what the problem is - I might also break it down into separate functions for the 8 parts it has - that way we can write more specific tests for it easier as well.

**Comment by ivyleavedtoadflax** [comment]
That's a good idea. I think there might be a 'combined dataset class' for which you can write methods to do the various tasks.

**Comment by maxwell8888** [comment]
are you suggesting that or saying that class already exists?

**Comment by ivyleavedtoadflax** [comment]
It's a suggestion. Although I'm not sure how it would interact with the other classes, for example `year_sector_data`. I can see that you would instantiate the `combined_data` class, and then you could run methods (which could be based on the extract functions) to load the data into class objects. Then you could have a method to combine all these objects together just like `combine_gva` currently does. The combined dataset could then be assigned to a global object and passed to the `year_sector_data` class as normal (and probably written to disk too).

**Pull request closed without merging**
