### PR TITLE
Feature/extract aps data

### PR DESCRIPTION
**Pull request by ghost**
To start from the ground up in fixing issue #81 - the extraction of data from an APS file. Please can you check that this function makes sense and that it is accompanied by suitable documentation and tests - and please let me know if there are other supporting files I need to include!

Following this functions that use this and analyse by year will be created.

### CODE REVIEW

**Comment by ivyleavedtoadflax** [comment]
This is a strange that it is failing on windows, but not linux. At any rate, I have pulled the failure logs from appveyor, and this is what they say:

```
1. Failure: extract_APS_data can extract data from a dummy spss file in the correct format (@test_extract_APS_data.R#16) 
 44 `APS` not equal to `APS_reference`.
 45 Component "INDC07M": Attributes: < Component "value.labels": Modes: numeric, character >
 46 Component "INDC07M": Attributes: < Component "value.labels": target is numeric, current is character >
 47 Component "INDC07S": Attributes: < Component "value.labels": Modes: numeric, character >
 48 Component "INDC07S": Attributes: < Component "value.labels": target is numeric, current is character >
 49 Component "INDSC07M": Attributes: < Component "value.labels": Modes: numeric, character >
 50 Component "INDSC07M": Attributes: < Component "value.labels": target is numeric, current is character >
 51 Component "INDSC07S": Attributes: < Component "value.labels": Modes: numeric, character >
 52 Component "INDSC07S": Attributes: < Component "value.labels": target is numeric, current is character >
 53 Component "SOC10M": Attributes: < Component "value.labels": Modes: numeric, character >
 54 Component "SOC10M": Attributes: < Component "value.labels": target is numeric, current is character >
 55 Component "SOC10S": Attributes: < Component "value.labels": Modes: numeric, character >
 56 Component "SOC10S": Attributes: < Component "value.labels": target is numeric, current is character >
 57 Component "INECAC05": Attributes: < Component "value.labels": Modes: numeric, character >
 58 Component "INECAC05": Attributes: < Component "value.labels": target is numeric, current is character >
 59 Component "SECJMBR": Attributes: < Component "value.labels": Modes: numeric, character >
 60 Component "SECJMBR": Attributes: < Component "value.labels": target is numeric, current is character >
 61 Component "SEX": Attributes: < Component "value.labels": Modes: numeric, character >
 62 Component "SEX": Attributes: < Component "value.labels": target is numeric, current is character >
 63 Component "AGES": Attributes: < Component "value.labels": Modes: numeric, character >
 64 Component "AGES": Attributes: < Component "value.labels": target is numeric, current is character >
 65 Component "ETHUK11": Attributes: < Component "value.labels": Modes: numeric, character >
 66 Component "ETHUK11": Attributes: < Component "value.labels": target is numeric, current is character >
 67 Component "NATOX7": Attributes: < Component "value.labels": Modes: numeric, character >
 68 Component "NATOX7": Attributes: < Component "value.labels": target is numeric, current is character >
 69 Component "FTPT": Attributes: < Component "value.labels": Modes: numeric, character >
 70 Component "FTPT": Attributes: < Component "value.labels": target is numeric, current is character >
 71 Component "HIQUL15D": Attributes: < Component "value.labels": Modes: numeric, character >
 72 Component "HIQUL15D": Attributes: < Component "value.labels": target is numeric, current is character >
 73 Component "GORWKR": Attributes: < Component "value.labels": Modes: numeric, character >
 74 Component "GORWKR": Attributes: < Component "value.labels": target is numeric, current is character >
 75 Component "GORWK2R": Attributes: < Component "value.labels": Modes: numeric, character >
 76 Component "GORWK2R": Attributes: < Component "value.labels": target is numeric, current is character >
 77 
```

It looks like there is a mismatch between the reference object and the object coming out of the function.

**Comment by ivyleavedtoadflax** [comment]
Ahhh ok I see you did add to packrat. I'll have a play.

**Comment by ivyleavedtoadflax** [comment]
Ahhh ok I see you did add to packrat. I'll have a play. Also might be worth looking at the haven package.

**Comment by DCMSstats** [comment]
Still failing on Travis because it can't find the package (haven this time). So probably something I'm doing wrong - any ideas?

**Comment by ivyleavedtoadflax** [comment]
I'll take a look

**Comment by ivyleavedtoadflax** [comment]
@DCMSstats I suspect this is to do with the Travis cache. To save time, travis caches all the packages we need, and so it just uses this cache instead of installing the packages afresh each time. This gets build time down from 20 mins to about 2. There is some info here: https://twitter.com/travisci/status/499961271358590976?lang=en. I'm going to flush the cache and restart the build, and hopefully that will be the fix.

**Comment by ivyleavedtoadflax** [comment]
This has partially fixed the problem. It's not an issue with the code @DCMSstats, it's purely down to the testing service. I'll continuing to look for a fix.

**Review by ivyleavedtoadflax — APPROVED** [review]
I converted `keep_variables` to an argument to make it easier to change, and updated the documentation to reflect this. Updated the Travis cache to include haven. All tests passing happily now.

**Review by ghost — COMMENTED** [review]
Makes sense to me.

**Pull request merged**
