### PR TITLE
give classes to gva datasets created by extract functions

### PR DESCRIPTION
**Pull request by maxwell8888**
this will allow subsequent functions such as combine_GVA_long() to
easily check if the data they have been passed is correct.

### CODE REVIEW

**Comment by ivyleavedtoadflax** [comment]
I'm not sure this is the right approach. That's suddenly a lot of classes! Have you thought about having a single combined_gva class which then has extract_... functions as methods? The various individual datasets and the combined datasets can then live in slots within this single class.

**Comment by maxwell8888** [comment]
I'm confused - how can a single class have multiple methods? I also don't see the benefit of having one large single object/class - it makes it more confusing for the user, and means when you pass the individual datasets to functions you can't check they are the right object easily - I think this is the best reason for using classes. I don't think having many classes is problem.

**Comment by ivyleavedtoadflax** [comment]
Have a think about model classes, they have both the plot and summary methods. I would build tests into the extract methods to ensure that you are loading the right shaped data. I disagree on it being simpler for the user to have multiple classes. It would mean the user has to handle multiple objects (one object of a different class for each incoming dataset). Compare this to having one object of one class (containing as objects the various datasets that are loaded with the extract functions, set up as methods and accessible through slots).

**Comment by maxwell8888** [comment]
Ok I see what you mean with the model class methods - although in the case of our publications, I don't think there is likely to be multiple methods for different classes - there will just be multiple functions. e.g. year_sector_data has functions but I don't think the equivalent class from the employment publication will require functions with the same name that behave differently for that class i.e. methods. I it is the use of classes is how S3 is useful - not so much methods. 

From the perspective of a statistician running the code I think it would be confusing to have everything lumped into an object - it is usual to simply have a different dataframe for each step in the analysis - that way users can easily sense check the data. And if you don't want the intermediate datasets you can just run the nested functions and only output the final dataset.

Would you be able to knock up some simple/pseudo code to demonstrate how you see the functions - from extract to output tie together in terms of classes, methods etc? I could do the same as well if it would be helpful. alternatively I could pop in to whitechapel today?

**Comment by ivyleavedtoadflax** [comment]
I'm WFH today - let me knock up some pseudocode, and then we can always discuss in person another day. Can pop by yours on the way to Whitechapel.

**Review by ivyleavedtoadflax — APPROVED** [review]
Keeping these in separate classes makes sense for user clarity.

**Pull request merged**
